sudo: false
language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install --upgrade pymc3
  - pip install --upgrade pytest pytest-cov coveralls
script:
  - pytest -v --cov=minimc test/
after_success:
  - coveralls
